BEGIN;
-- Reset (safe for reruns)
DROP TABLE IF EXISTS teaching_assignment CASCADE;
DROP TABLE IF EXISTS program_course CASCADE;
DROP TABLE IF EXISTS student CASCADE;

DROP TABLE IF EXISTS consultant CASCADE;
DROP TABLE IF EXISTS consultant_company CASCADE;

DROP TABLE IF EXISTS educator CASCADE;
DROP TABLE IF EXISTS employee CASCADE;

DROP TABLE IF EXISTS person_sensitive CASCADE;
DROP TABLE IF EXISTS person CASCADE;

DROP TABLE IF EXISTS class CASCADE;
DROP TABLE IF EXISTS course CASCADE;
DROP TABLE IF EXISTS program CASCADE;
DROP TABLE IF EXISTS facility CASCADE;

-- =========================
-- DB core tables
-- =========================

CREATE TABLE facility (
    facility_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(100) NOT NULL,
    city           VARCHAR(50) NOT NULL,
    postal_code    VARCHAR(20),
    address        VARCHAR(200),
    capacity       INT CHECK (capacity IS NULL OR capacity > 0),
    room_type      VARCHAR(50),
    hc_accessible  BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE program (
    program_id      VARCHAR(20) PRIMARY KEY,
    program_code    VARCHAR(20) UNIQUE NOT NULL,
    program_name    VARCHAR(100) NOT NULL,
    points_total    INT CHECK (points_total IS NULL OR points_total > 0),
    decision_number INT NOT NULL
);

CREATE TABLE course (
    course_id           VARCHAR(20) PRIMARY KEY,
    course_code         VARCHAR(20) UNIQUE NOT NULL,
    course_name         VARCHAR(100) NOT NULL,
    course_description  TEXT,
    course_points       INT CHECK (course_points IS NULL OR course_points > o)
);

-- =========================
-- Super/subtypes(shared PK)
-- =========================

CREATE TABLE person (
    person_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name  VARCHAR(50) NOT NULL,
    last_name   VARCHAR(50) NOT NULL,
    email       VARCHAR(100) UNIQUE NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE person_sensitive (
    person_id           INT PRIMARY KEY REFERENCES person(person_id) ON DELETE CASCADE,
    personal_number     VARCHAR(13) UNIQUE NOT NULL,
    private_email       VARCHAR(100),
    home_address        VARCHAR(200),
    phone_number        VARCHAR(15)
);

CREATE TABLE employee (
    person_id           INT PRIMARY KEY REFERENCES person(person_id) ON DELETE CASCADE,
    title               VARCHAR(100),
    employee_nr         VARCHAR(20) UNIQUE NOT NULL,
    employee_salary     NUMERIC(10,2) NOT NULL CHECK (employee_salary > 0),
    employment_type     VARCHAR(20) NOT NULL
);

CREATE TABLE educator (
    person_id           INT PRIMARY KEY REFERENCES person(person_id) ON DELETE CASCADE,
    competence_area     VARCHAR(100) NOT NULL
);

CREATE TABLE consultant (
    person_id               INT PRIMARY KEY REFERENCES educator(person_id) ON DELETE CASCADE,
    consultant_company_id   INT NOT NULL REFERENCES consultant_company(consultant_company_id),
    hourly_rate             NUMERIC(10,2) NOT NULL CHECK (hourly_rate > 0)
);

CREATE TABLE consultant_company (
    consultant_company_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_number              VARCHAR(11) UNIQUE NOT NULL,
    name                    VARCHAR(100) NOT NULL, 
    has_f_skatt             BOOLEAN NOT NULL DEFAULT FALSE,
    address                 VARCHAR(200)
);